name: terraform-destroy
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform-Destory"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TERRAFORM_VERSION: 0.12.20

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@v0.7.1
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
